name: Checks
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Lint Assets
        run: |
          which magick
          which identify

      - name: Lint Assets
        run: python verify.py