name: Checks
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  checks:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Lint Assets
        run: ./verify.py